/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package garadragontrainer;

public class JFrameGara extends javax.swing.JFrame {

    private Drago d1, d2, d3, d4;
    private ControlloVincitore c; // Usa la classe separata
    private ControlloAnimazione anim1, anim2, anim3, anim4; // le animazioni
    private ControlloDanniCasuali dannoCasuale2, dannoCasuale3, dannoCasuale4;

    public JFrameGara() {
        initComponents();
        getContentPane().setLayout(null);
        setupIconLabels();
        

    }
	/**
     * Sistema le label delle icone dei draghi
     * Le posiziona sopra le progress bar e le rende visibili
     */
    private void setupIconLabels() {
        // Imposta dimensioni corrette (non 0!)
        lblIconDrago1.setSize(50, 50);
        lblIconDrago2.setSize(50, 50);
        lblIconDrago3.setSize(50, 50);
        lblIconDrago4.setSize(50, 50);
        
        // Posiziona le label sopra le progress bar (posizione iniziale)
        // X = posizione X della progress bar + margine sinistro
        // Y = posizione Y della progress bar - 55 (sopra la barra)
        lblIconDrago1.setLocation(141, 136 - 55);
        lblIconDrago2.setLocation(141, 250 - 55);
        lblIconDrago3.setLocation(141, 372 - 55);
        lblIconDrago4.setLocation(141, 507 - 55);
        
        // Rendi visibili le label portandole in primo piano
        lblIconDrago1.setVisible(true);
        lblIconDrago2.setVisible(true);
        lblIconDrago3.setVisible(true);
        lblIconDrago4.setVisible(true);
        
        // Porta le label in primo piano (sopra tutto)
        getContentPane().setComponentZOrder(lblIconDrago1, 0);
        getContentPane().setComponentZOrder(lblIconDrago2, 0);
        getContentPane().setComponentZOrder(lblIconDrago3, 0);
        getContentPane().setComponentZOrder(lblIconDrago4, 0);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGioca = new javax.swing.JButton();
        lblVincitore4 = new javax.swing.JLabel();
        lblVincitore3 = new javax.swing.JLabel();
        btnAvvia = new javax.swing.JButton();
        lblDrago4 = new javax.swing.JLabel();
        lblDrago3 = new javax.swing.JLabel();
        lblDrago2 = new javax.swing.JLabel();
        lblDrago1 = new javax.swing.JLabel();
        pgrDrago1 = new javax.swing.JProgressBar();
        btnPausa = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblVincitore1 = new javax.swing.JLabel();
        pgrDrago2 = new javax.swing.JProgressBar();
        pgrDrago3 = new javax.swing.JProgressBar();
        lblVincitore2 = new javax.swing.JLabel();
        pgrDrago4 = new javax.swing.JProgressBar();
        lblIconDrago2 = new javax.swing.JLabel();
        lblIconDrago1 = new javax.swing.JLabel();
        lblIconDrago3 = new javax.swing.JLabel();
        lblIconDrago4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));
        setMaximumSize(new java.awt.Dimension(910, 814));
        setPreferredSize(new java.awt.Dimension(910, 750));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(18, 22, 40));
        jPanel1.setDoubleBuffered(false);
        jPanel1.setMaximumSize(new java.awt.Dimension(910, 814));
        jPanel1.setMinimumSize(new java.awt.Dimension(910, 750));
        jPanel1.setPreferredSize(new java.awt.Dimension(910, 750));
        jPanel1.setLayout(null);

        btnGioca.setBackground(new java.awt.Color(114, 35, 90));
        btnGioca.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btnGioca.setForeground(new java.awt.Color(255, 255, 255));
        btnGioca.setText("Gioca");
        btnGioca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiocaActionPerformed(evt);
            }
        });
        jPanel1.add(btnGioca);
        btnGioca.setBounds(250, 580, 280, 70);

        lblVincitore4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblVincitore4.setForeground(new java.awt.Color(150, 150, 150));
        lblVincitore4.setText(" ");
        jPanel1.add(lblVincitore4);
        lblVincitore4.setBounds(670, 500, 60, 40);

        lblVincitore3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblVincitore3.setForeground(new java.awt.Color(180, 180, 180));
        lblVincitore3.setText(" ");
        jPanel1.add(lblVincitore3);
        lblVincitore3.setBounds(670, 360, 60, 40);

        btnAvvia.setBackground(new java.awt.Color(60, 110, 80));
        btnAvvia.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnAvvia.setForeground(new java.awt.Color(255, 255, 255));
        btnAvvia.setText("Avvia");
        btnAvvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvviaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAvvia);
        btnAvvia.setBounds(780, 90, 100, 70);

        lblDrago4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblDrago4.setForeground(new java.awt.Color(210, 180, 100));
        lblDrago4.setText("Drago 4");
        jPanel1.add(lblDrago4);
        lblDrago4.setBounds(19, 507, 54, 16);

        lblDrago3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblDrago3.setForeground(new java.awt.Color(210, 180, 100));
        lblDrago3.setText("Drago 3");
        jPanel1.add(lblDrago3);
        lblDrago3.setBounds(19, 372, 62, 16);

        lblDrago2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblDrago2.setForeground(new java.awt.Color(210, 180, 100));
        lblDrago2.setText("Drago 2");
        jPanel1.add(lblDrago2);
        lblDrago2.setBounds(19, 250, 59, 16);

        lblDrago1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblDrago1.setForeground(new java.awt.Color(210, 180, 100));
        lblDrago1.setText("Drago 1");
        jPanel1.add(lblDrago1);
        lblDrago1.setBounds(19, 136, 54, 16);

        pgrDrago1.setBackground(new java.awt.Color(153, 153, 153));
        pgrDrago1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(pgrDrago1);
        pgrDrago1.setBounds(141, 136, 500, 28);

        btnPausa.setBackground(new java.awt.Color(140, 100, 30));
        btnPausa.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnPausa.setForeground(new java.awt.Color(255, 255, 255));
        btnPausa.setText("Pausa");
        btnPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPausa);
        btnPausa.setBounds(780, 270, 100, 70);

        btnReset.setBackground(new java.awt.Color(70, 75, 90));
        btnReset.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset);
        btnReset.setBounds(780, 460, 100, 70);

        lblVincitore1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblVincitore1.setForeground(new java.awt.Color(255, 210, 60));
        lblVincitore1.setText(" ");
        jPanel1.add(lblVincitore1);
        lblVincitore1.setBounds(670, 130, 60, 40);

        pgrDrago2.setBackground(new java.awt.Color(255, 255, 51));
        pgrDrago2.setForeground(new java.awt.Color(51, 204, 255));
        jPanel1.add(pgrDrago2);
        pgrDrago2.setBounds(141, 250, 500, 28);

        pgrDrago3.setBackground(new java.awt.Color(255, 102, 0));
        pgrDrago3.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(pgrDrago3);
        pgrDrago3.setBounds(141, 372, 500, 28);

        lblVincitore2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblVincitore2.setForeground(new java.awt.Color(200, 200, 200));
        lblVincitore2.setText(" ");
        jPanel1.add(lblVincitore2);
        lblVincitore2.setBounds(670, 240, 60, 40);

        pgrDrago4.setBackground(new java.awt.Color(153, 51, 0));
        pgrDrago4.setForeground(new java.awt.Color(51, 204, 0));
        jPanel1.add(pgrDrago4);
        pgrDrago4.setBounds(141, 507, 500, 28);

        lblIconDrago2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/stormfly.gif"))); // NOI18N
        lblIconDrago2.setMaximumSize(new java.awt.Dimension(60, 60));
        lblIconDrago2.setMinimumSize(new java.awt.Dimension(50, 50));
        lblIconDrago2.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(lblIconDrago2);
        lblIconDrago2.setBounds(140, 160, 230, 90);

        lblIconDrago1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/thootless.gif"))); // NOI18N
        lblIconDrago1.setText(" ");
        lblIconDrago1.setMaximumSize(new java.awt.Dimension(50, 50));
        lblIconDrago1.setMinimumSize(new java.awt.Dimension(50, 50));
        lblIconDrago1.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(lblIconDrago1);
        lblIconDrago1.setBounds(140, 40, 60, 90);

        lblIconDrago3.setBackground(new java.awt.Color(208, 242, 242));
        lblIconDrago3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/hookfang.gif"))); // NOI18N
        lblIconDrago3.setText(" ");
        lblIconDrago3.setMaximumSize(new java.awt.Dimension(50, 50));
        lblIconDrago3.setMinimumSize(new java.awt.Dimension(50, 50));
        lblIconDrago3.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(lblIconDrago3);
        lblIconDrago3.setBounds(140, 290, 70, 80);

        lblIconDrago4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/barfBelch.gif"))); // NOI18N
        lblIconDrago4.setText(" ");
        lblIconDrago4.setMaximumSize(new java.awt.Dimension(50, 50));
        lblIconDrago4.setMinimumSize(new java.awt.Dimension(50, 50));
        lblIconDrago4.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(lblIconDrago4);
        lblIconDrago4.setBounds(140, 420, 90, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 910, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvviaActionPerformed
      //bottoni
      btnPausa.setEnabled(true);
        btnReset.setEnabled(true);
        btnGioca.setEnabled(true);
    // Crea le animazioni e carica le gif
    anim1 = new ControlloAnimazione(lblIconDrago1, pgrDrago1, getContentPane());
    anim2 = new ControlloAnimazione(lblIconDrago2, pgrDrago2, getContentPane());
    anim3 = new ControlloAnimazione(lblIconDrago3, pgrDrago3, getContentPane());
    anim4 = new ControlloAnimazione(lblIconDrago4, pgrDrago4, getContentPane());
    
 
   // Carica le immagini gif
anim1.caricaIconaDrago("src/immagini/thootless.gif");
anim2.caricaIconaDrago("src/immagini/stormfly.gif");
anim3.caricaIconaDrago("src/immagini/hookfang.gif");
anim4.caricaIconaDrago("src/immagini/barfBelch.gif");
    // Crea i draghi con le animazioni
    d1 = new Drago(pgrDrago1, anim1);
    d2 = new Drago(pgrDrago2, anim2);
    d3 = new Drago(pgrDrago3, anim3);
    d4 = new Drago(pgrDrago4, anim4);

    Thread t1 = new Thread(d1);
    Thread t2 = new Thread(d2);
    Thread t3 = new Thread(d3);
    Thread t4 = new Thread(d4);

    t1.start();
    t2.start();
    t3.start();
    t4.start();
    
    // Crea e avvia il controllo vincitori
    c = new ControlloVincitore (d1, d2, d3, d4, lblVincitore1, lblVincitore2, lblVincitore3, lblVincitore4);
    c.avvia();
    btnAvvia.setEnabled(false);
            // Avvia i danni casuali per gli altri 3 draghi (non il giocatore!)
        dannoCasuale2 = new ControlloDanniCasuali(d2);
        dannoCasuale3 = new ControlloDanniCasuali(d3);
        dannoCasuale4 = new ControlloDanniCasuali(d4);
        
        dannoCasuale2.avvia();
        dannoCasuale3.avvia();
        dannoCasuale4.avvia();

    }//GEN-LAST:event_btnAvviaActionPerformed

    private void btnPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausaActionPerformed

        if (d1 == null)  return;
        if (c != null) c.ferma();
        
         // Ferma i danni casuali
        if (dannoCasuale2 != null) dannoCasuale2.ferma();
        if (dannoCasuale3 != null) dannoCasuale3.ferma();
        if (dannoCasuale4 != null) dannoCasuale4.ferma();
        

        if (btnPausa.getText().equals("Pausa")) {
            d1.pausa();
            d2.pausa();
            d3.pausa();
            d4.pausa();
            btnPausa.setText("Riprendi");
        } else {
            d1.riprendi();
            d2.riprendi();
            d3.riprendi();
            d4.riprendi();
              // Riavvia i danni casuali
            if (dannoCasuale2 != null) dannoCasuale2.avvia();
            if (dannoCasuale3 != null) dannoCasuale3.avvia();
            if (dannoCasuale4 != null) dannoCasuale4.avvia();
            
            btnPausa.setForeground(java.awt.Color.WHITE);
        btnPausa.setText("Pausa");
        }

    }//GEN-LAST:event_btnPausaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed

        if (d1 == null) {
            return;
        }

        // Ferma il controllo vincitori
        if (c != null) {
            c.ferma();
        }
 // Ferma i danni casuali
        if (dannoCasuale2 != null) dannoCasuale2.ferma();
        if (dannoCasuale3 != null) dannoCasuale3.ferma();
        if (dannoCasuale4 != null) dannoCasuale4.ferma();
        
        d1.reset();
        d2.reset();
        d3.reset();
        d4.reset();

        pgrDrago1.setValue(0);
        pgrDrago2.setValue(0);
        pgrDrago3.setValue(0);
        pgrDrago4.setValue(0);

        lblVincitore1.setText(" ");
        lblVincitore2.setText(" ");
        lblVincitore3.setText(" ");
        lblVincitore4.setText(" ");
        //pulsanti
        btnAvvia.setEnabled(true);
        btnPausa.setEnabled(false);
        btnReset.setEnabled(false);
        btnGioca.setEnabled(false);
        setupIconLabels(); //mette le icone all'inizio 
        btnPausa.setForeground(java.awt.Color.WHITE);
        btnPausa.setText("Pausa");
		
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnGiocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiocaActionPerformed
          if (d1 != null){
              new JGioca(d1).setVisible(true);
          }else {
              javax.swing.JOptionPane.showMessageDialog(this, 
                "Devi prima avviare la gara!", 
                "Attenzione", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
          }
        
        
    }//GEN-LAST:event_btnGiocaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGara().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvvia;
    private javax.swing.JButton btnGioca;
    private javax.swing.JButton btnPausa;
    private javax.swing.JButton btnReset;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDrago1;
    private javax.swing.JLabel lblDrago2;
    private javax.swing.JLabel lblDrago3;
    private javax.swing.JLabel lblDrago4;
    private javax.swing.JLabel lblIconDrago1;
    private javax.swing.JLabel lblIconDrago2;
    private javax.swing.JLabel lblIconDrago3;
    private javax.swing.JLabel lblIconDrago4;
    private javax.swing.JLabel lblVincitore1;
    private javax.swing.JLabel lblVincitore2;
    private javax.swing.JLabel lblVincitore3;
    private javax.swing.JLabel lblVincitore4;
    private javax.swing.JProgressBar pgrDrago1;
    private javax.swing.JProgressBar pgrDrago2;
    private javax.swing.JProgressBar pgrDrago3;
    private javax.swing.JProgressBar pgrDrago4;
    // End of variables declaration//GEN-END:variables
}