                                                                                                                                                                         /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package garadragontrainer;

public class JFrameGara extends javax.swing.JFrame {

       private Drago d1, d2, d3, d4;
    private ControlloVincitore c; // Usa la classe separata
    private ControlloAnimazione anim1, anim2, anim3, anim4; // le animazioni

    public JFrameGara() {
        initComponents();
        getContentPane().setLayout(null);
    
    // Crea le label per le icone
    lblIconDrago1 = new javax.swing.JLabel();
    lblIconDrago2 = new javax.swing.JLabel();
    lblIconDrago3 = new javax.swing.JLabel();
    lblIconDrago4 = new javax.swing.JLabel();
    
    // Aggiungi al pannello
    getContentPane().add(lblIconDrago1);
    getContentPane().add(lblIconDrago2);
    getContentPane().add(lblIconDrago3);
    getContentPane().add(lblIconDrago4);
    
    // Imposta size
    lblIconDrago1.setSize(40, 40);
    lblIconDrago2.setSize(40, 40);
    lblIconDrago3.setSize(40, 40);
    lblIconDrago4.setSize(40, 40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pgrDrago2 = new javax.swing.JProgressBar();
        pgrDrago3 = new javax.swing.JProgressBar();
        pgrDrago4 = new javax.swing.JProgressBar();
        pgrDrago1 = new javax.swing.JProgressBar();
        lblDrago1 = new javax.swing.JLabel();
        lblDrago2 = new javax.swing.JLabel();
        lblDrago3 = new javax.swing.JLabel();
        lblDrago4 = new javax.swing.JLabel();
        btnAvvia = new javax.swing.JButton();
        btnPausa = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblVincitore1 = new javax.swing.JLabel();
        lblVincitore2 = new javax.swing.JLabel();
        lblVincitore3 = new javax.swing.JLabel();
        lblVincitore4 = new javax.swing.JLabel();
        lblIconDrago2 = new javax.swing.JLabel();
        lblIconDrago1 = new javax.swing.JLabel();
        lblIconDrago3 = new javax.swing.JLabel();
        lblIconDrago4 = new javax.swing.JLabel();
        btnGioca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pgrDrago2.setBackground(new java.awt.Color(255, 255, 51));
        pgrDrago2.setForeground(new java.awt.Color(51, 204, 255));

        pgrDrago3.setBackground(new java.awt.Color(255, 102, 0));
        pgrDrago3.setForeground(new java.awt.Color(204, 0, 0));

        pgrDrago4.setBackground(new java.awt.Color(153, 51, 0));
        pgrDrago4.setForeground(new java.awt.Color(51, 204, 0));

        pgrDrago1.setBackground(new java.awt.Color(153, 153, 153));
        pgrDrago1.setForeground(new java.awt.Color(0, 0, 0));

        lblDrago1.setText("Drago 1");

        lblDrago2.setText("Drago 2");

        lblDrago3.setText("Drago 3");

        lblDrago4.setText("Drago 4");

        btnAvvia.setBackground(new java.awt.Color(150, 190, 220));
        btnAvvia.setText("Avvia");
        btnAvvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvviaActionPerformed(evt);
            }
        });

        btnPausa.setBackground(new java.awt.Color(150, 200, 150));
        btnPausa.setText("Pausa");
        btnPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausaActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(200, 200, 200));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblVincitore1.setText(" ");

        lblVincitore2.setForeground(new java.awt.Color(255, 204, 0));
        lblVincitore2.setText(" ");

        lblVincitore3.setForeground(new java.awt.Color(255, 102, 0));
        lblVincitore3.setText(" ");

        lblVincitore4.setForeground(new java.awt.Color(153, 51, 0));
        lblVincitore4.setText(" ");

        lblIconDrago2.setText(" ");

        lblIconDrago1.setText(" ");

        lblIconDrago3.setText(" ");

        lblIconDrago4.setText(" ");

        btnGioca.setBackground(new java.awt.Color(102, 102, 255));
        btnGioca.setText("Gioca");
        btnGioca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiocaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnAvvia, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(btnPausa, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDrago3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrago4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrago2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrago1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pgrDrago1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pgrDrago4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pgrDrago3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIconDrago4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIconDrago3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIconDrago1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVincitore2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblVincitore1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(199, 199, 199))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblVincitore4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblVincitore3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGioca)
                                .addGap(41, 41, 41))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pgrDrago2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIconDrago2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblIconDrago1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pgrDrago1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrago1)
                    .addComponent(lblVincitore1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(lblIconDrago2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDrago2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pgrDrago2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(lblIconDrago3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVincitore3)
                                .addGap(65, 65, 65)
                                .addComponent(lblVincitore4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDrago3)
                                    .addComponent(pgrDrago3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(lblIconDrago4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDrago4)
                                    .addComponent(pgrDrago4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnPausa, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAvvia, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnGioca, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVincitore2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvviaActionPerformed
                                        
    // Crea le animazioni e carica le gif
    anim1 = new ControlloAnimazione(lblIconDrago1, pgrDrago1, getContentPane());
    anim2 = new ControlloAnimazione(lblIconDrago2, pgrDrago2, getContentPane());
    anim3 = new ControlloAnimazione(lblIconDrago3, pgrDrago3, getContentPane());
    anim4 = new ControlloAnimazione(lblIconDrago4, pgrDrago4, getContentPane());
    
 
   // Carica le immagini gif
anim1.caricaIconaDrago("src/immagini/stormfly.gif");
anim2.caricaIconaDrago("src/immagini/stormfly.gif");
anim3.caricaIconaDrago("src/immagini/stormfly.gif");
anim4.caricaIconaDrago("src/immagini/stormfly.gif");
    // Crea i draghi con le animazioni
    d1 = new Drago(pgrDrago1, anim1);
    d2 = new Drago(pgrDrago2, anim2);
    d3 = new Drago(pgrDrago3, anim3);
    d4 = new Drago(pgrDrago4, anim4);

    Thread t1 = new Thread(d1);
    Thread t2 = new Thread(d2);
    Thread t3 = new Thread(d3);
    Thread t4 = new Thread(d4);

    t1.start();
    t2.start();
    t3.start();
    t4.start();
    
    // Crea e avvia il controllo vincitori
    c = new ControlloVincitore (d1, d2, d3, d4, lblVincitore1, lblVincitore2, lblVincitore3, lblVincitore4);
    c.avvia();

    }//GEN-LAST:event_btnAvviaActionPerformed

    private void btnPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausaActionPerformed
    
    if (d1 == null) return;
    
    if (btnPausa.getText().equals("Pausa")) {
        d1.pausa();
        d2.pausa();
        d3.pausa();
        d4.pausa();
        btnPausa.setText("Riprendi");
    } else {
        d1.riprendi();
        d2.riprendi();
        d3.riprendi();
        d4.riprendi();
        btnPausa.setText("Pausa");
    }

    }//GEN-LAST:event_btnPausaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
    if (d1 == null) return;
    
    // Ferma il controllo vincitori
    if (c != null) {
        c.ferma();
    }
    
    d1.reset();
    d2.reset();
    d3.reset();
    d4.reset();
    
    pgrDrago1.setValue(0);
    pgrDrago2.setValue(0);
    pgrDrago3.setValue(0);
    pgrDrago4.setValue(0);
    
    lblVincitore1.setText(" ");
    lblVincitore2.setText(" ");
    lblVincitore3.setText(" ");
    lblVincitore4.setText(" ");
    
    btnPausa.setText("Pausa");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnGiocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiocaActionPerformed
          new JGioca().setVisible(true);
    }//GEN-LAST:event_btnGiocaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGara().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvvia;
    private javax.swing.JButton btnGioca;
    private javax.swing.JButton btnPausa;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lblDrago1;
    private javax.swing.JLabel lblDrago2;
    private javax.swing.JLabel lblDrago3;
    private javax.swing.JLabel lblDrago4;
    private javax.swing.JLabel lblIconDrago1;
    private javax.swing.JLabel lblIconDrago2;
    private javax.swing.JLabel lblIconDrago3;
    private javax.swing.JLabel lblIconDrago4;
    private javax.swing.JLabel lblVincitore1;
    private javax.swing.JLabel lblVincitore2;
    private javax.swing.JLabel lblVincitore3;
    private javax.swing.JLabel lblVincitore4;
    private javax.swing.JProgressBar pgrDrago1;
    private javax.swing.JProgressBar pgrDrago2;
    private javax.swing.JProgressBar pgrDrago3;
    private javax.swing.JProgressBar pgrDrago4;
    // End of variables declaration//GEN-END:variables
}