/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package garadragontrainer;

/**
 *
 * @author lucia
 */
public class JGioca extends javax.swing.JFrame {
  private ControlloVideo cv;
  private ControlloAttacco ca;
  private Drago dragoGiocatore;
    /**
     * Creates new form JGioca
     */
    public JGioca( Drago dragoGiocatore) {
        this.dragoGiocatore= dragoGiocatore;
        initComponents();
        setupVideo();
        setupAttacchi();
    }
        public JGioca(){
        this(null);
        }
private void setupVideo() {
        // Crea l'istanza del controllo video
        cv = new ControlloVideo(lblVideo);
        
        // Carica la GIF (dimensione originale)
        cv.caricaVideo("src/immagini/Video_Pov1.gif");
        
        
    }
    private void setupAttacchi() {
        if (dragoGiocatore == null) {
            System.out.println("Errore! il drago non esiste");
            btnSchiva.setEnabled(false);
            return;
        }
        //crea controllo attacchi - PASSA ANCHE IL PANNELLO!
        ca = new ControlloAttacco(lblAttacco, btnSchiva, dragoGiocatore, jPanel1);
        //carica la gif di attacco 
        ca.caricaGifAttacco("src/immagini/DragoAttacco_small.gif");
        //avvia gli attacchi casuali 
        ca.avvia();
    }
    
    
    //ferma gli attacchi quando si chiude la finestra 
    public void fermaAttacchi(){
        if (ca != null){
            ca.ferma();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAttacco = new javax.swing.JLabel();
        lblVideo = new javax.swing.JLabel();
        btnSchiva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(420, 700));

        jPanel1.setBackground(new java.awt.Color(18, 22, 40));
        jPanel1.setLayout(null);

        lblAttacco.setMaximumSize(new java.awt.Dimension(500, 500));
        lblAttacco.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel1.add(lblAttacco);
        lblAttacco.setBounds(220, 0, 180, 150);

        lblVideo.setMaximumSize(new java.awt.Dimension(1000, 500));
        lblVideo.setMinimumSize(new java.awt.Dimension(100, 50));
        lblVideo.setName(""); // NOI18N
        lblVideo.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel1.add(lblVideo);
        lblVideo.setBounds(0, 0, 400, 500);

        btnSchiva.setBackground(new java.awt.Color(140, 35, 35));
        btnSchiva.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 2, 24)); // NOI18N
        btnSchiva.setForeground(new java.awt.Color(255, 255, 255));
        btnSchiva.setText("Schiva!");
        btnSchiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSchivaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSchiva);
        btnSchiva.setBounds(110, 550, 160, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSchivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSchivaActionPerformed
       if(ca != null){
           ca.schivaAttacco();
       }
    }//GEN-LAST:event_btnSchivaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Ferma gli attacchi quando si chiude la finestra
        fermaAttacchi();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JGioca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JGioca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JGioca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JGioca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JGioca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSchiva;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAttacco;
    private javax.swing.JLabel lblVideo;
    // End of variables declaration//GEN-END:variables
}